const Courses = [
    {
        id: "1",
        title: "Web Development",
        image: require("../../../../assets/course/web.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "2",
        title: "Graphic Designing",
        image: require("../../../../assets/course/graphic.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "3",
        title: "Coding Fundamentals",
        image: require("../../../../assets/course/coding.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "4",
        title: "Ethical Hacking",
        image: require("../../../../assets/course/hacking.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "5",
        title: "Data Structure",
        image: require("../../../../assets/course/data.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
    {
        id: "6",
        title: "Corel Draw",
        image: require("../../../../assets/course/corel.png"),
        description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem ex vero laboriosam culpa corporis esse ipsum rem fuga! Tempora, soluta!",
        course1: "HTML",
        course2: "CSS",
        course3: "JavaScript",
        price: 5000,
    },
];

export default Courses;